name = "subscribe"
main = "src/worker.ts"
compatibility_date = "2023-07-10"

# Variable bindings. These are arbitrary, plaintext strings (similar to environment variables)
# Note: Use secrets to store sensitive data.
# Docs: https://developers.cloudflare.com/workers/platform/environment-variables
# [vars]
# MY_VARIABLE = "production_value"

# Bind a KV Namespace. Use KV as persistent storage for small key-value pairs.
# Docs: https://developers.cloudflare.com/workers/runtime-apis/kv
[[kv_namespaces]]
binding = "SUBSCRIBE"
id = "1e41e1aadc90483d9dd841bfb24f4768"
preview_id = "1e41e1aadc90483d9dd841bfb24f4768"

[triggers]
crons = ["0 */2 * * *"]